language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
before_install:
  - export TZ=Europe/Warsaw
before_script:
  - echo 'Europe/Warsaw' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
script:
  - npm test
  - npm run build
